#!/bin/bash
################################################################################
# Script : /tools/load-all-modules
# Purpose: Load all Kernel modules from /lib/modules in order to light up
#          hardware. This is useful when onboarding Slackware ARM to new
#          Hardware Models.
#
#          Typically you would boot into the slkpbs shell, exit stages 1 & 2
#          and at stage three (when the AArch64 base line set of modules has
#          been loaded), call this script.
# Author : Stuart Winter <mozes@slackware.com>
# Version: 1.00
# Note...: You might need to restrict the scope of 'find' though, incase you
#          bring the system down (it's always possible that loading some modules
#          will cause a Kernel panic).
################################################################################

find /lib/modules/$(uname -r) -type f -name '*.ko.*' | \
   while read mod; do
      modprobe $( basename $mod .ko.xz )
   done
